test(local-server): disabled Restify-related tests on Node 18 since Restify doesn't support it
Restify does monkey-patching of the Request object,
and tries to overwrite `closed` - https://github.com/restify/node-restify/blob/839fb4a2b5e5434d43e60e1abb936e153c659c31/lib/request.js#L848

However, on Node 18 closed is a getter not a property, so this results in
TypeError: Cannot set property closed of #<Readable> which has only a getter

Related issue restify/node-restify#1888

re #1243